### ISSUE TITLE
Bug: The main page is showing blank blue screen

### ISSUE THREAD

**Issue by moin-gun** [HeyPuter/puter#1336]
### Issue Description

The main page puter.com is showing blank blue page. Tried clearing cookie, different browser and different network and devices too.

![Image](https://github.com/user-attachments/assets/402174c3-dfcd-4600-8c2e-716f35dded48)

### Deployment

- [x] Production (puter.com)
- [ ] Development (`npm run start`)
- [ ] Docker (via `docker run`)
- [ ] Docker (via `docker-compose`)

**Comment by jelveh** [comment]
This is fixed now. Please try again.

**Comment by moin-gun** [comment]
@jelveh it is still same. I refreshed so many times, I cleared cookies twice. Tried in incognito mode as well. I hope my account is not banned.

![Image](https://github.com/user-attachments/assets/43d28f2e-9f0d-4f88-8aa0-ab8632b0c42f)

**Comment by moin-gun** [comment]
@jelveh kindly look into it, I am still facing this issue. I am accessing from India.

**Comment by jelveh** [comment]
Could you try one more time? I'm pretty sure it's fixed now.

**Comment by moin-gun** [comment]
@jelveh Thanks a lot, now it is all working!
