### ISSUE TITLE
ui improvement: allow dragging table rows in "usage details" to see full content

### ISSUE THREAD

**Issue by XiaochenCui** [HeyPuter/puter#1847]
some resource names in the usage table are cut off with “...”. it would be helpful if users could drag or resize the column to see the full text. alternatively, showing the full name on hover would also work.

<img width="523" height="279" alt="Image" src="https://github.com/user-attachments/assets/f8226886-eed6-414c-82d2-8201c672206d" />

**Comment by jelveh** [comment]
@bomberfish this would be a good issue to pick up for you as well

**Comment by utkubakir** [comment]
fixed on #1828 -- it shows on hover

**Comment by KernelDeimos** [comment]
GitHub doesn't understand the revert in #1931 (I guess) so this issue remained closed.

**Comment by tmchow** [comment]
Implemented in https://github.com/HeyPuter/puter/pull/2785 - adds title attributes to all td elements in both Settings and Dashboard usage tables so the full text shows on hover.
