### ISSUE TITLE
Issues with local-hosted KV store

### ISSUE THREAD

**Issue by AtkinsSJ** [HeyPuter/puter#206]
I'm noticing a couple of problems with `puter.kv` when running locally. At least, I *assume* they are problems; I want to check before messing with them.

Firstly, `puter.kv.get()`'s Promise seems to be returning the wrong type of data, when locally hosted. Specifically, it's returning `{ "value": "FOO" }` instead of just `"FOO"`. This means that after refreshing the page, the `language` and `clock_visible` settings get corrupted.

Second, each time a KV is saved, it appends to the database table instead of updating the existing record.

The steps to reproduce both of these are:

1. Launch a local Puter instance
2. Open settings
3. Go to the "Language" tab
4. Click on a few different languages
5. Refresh the page

The things to notice:
- Whichever language you had, the UI is now in English again. (The default when nothing is set.)
- Opening the Language settings again, nothing is selected.
- Opening the Local Storage browser inspector, the `user_preferences` value has something like `{"show_hidden_files":null,"language":{"value":"de"},"clock_visible":{"value":"show"}}`, with the `language` wrapped in `{ "value": "..." }`.
- If you open the sqlite database up, the same key has multiple rows, as below: (Second issue above.)
![image](https://github.com/HeyPuter/puter/assets/222642/65aee3c5-378a-4251-80dc-56278ec697cd)
(Side note, https://sqlitebrowser.org/ is pretty good for browsing sqlite files.)

**Comment by KernelDeimos** [comment]
[fixed](https://github.com/HeyPuter/puter/commit/0651aab1bea9cd84b3b220e302f2720ca44a1972)

**Comment by AtkinsSJ** [comment]
Bringing this back up because the duplicate-rows thing is still happening, and causing issues for me now:
- When saving, a new row is appended
- When loading, it seems to use the first row for the given key
