### ISSUE TITLE
docker-compose Error log

### ISSUE THREAD

**Issue by frankzzw** [HeyPuter/puter#209]
> puter.com@1.0.0 start
> node run-selfhosted.js

Boot logger started :)
[BOOT/INFO] Checking path `$CONFIG_PATH` for configuration...
[BOOT/INFO] -> doing `require_if_not_undefined` on path [undefined]...
[BOOT/INFO] -> `require_if_not_undefined` doesn't like this path
[BOOT/INFO] Checking path `/etc/puter` for configuration...
[BOOT/INFO] -> doing `skip_if_not_exists` on path `/etc/puter`...
[BOOT/INFO] -> `skip_if_not_exists` doesn't like this path
[BOOT/INFO] Checking path `/opt/puter/app/volatile/config` for configuration...
[BOOT/INFO] -> doing `skip_if_not_in_repo` on path `/opt/puter/app/volatile/config`...
[BOOT/INFO] -> doing `require_read_permission` on path `/opt/puter/app/volatile/config`...
[BOOT/INFO] USING `/opt/puter/app/volatile/config` for configuration.
[BOOT/INFO] Checking path `$RUNTIME_PATH` for working directory...
[BOOT/INFO] -> doing `require_if_not_undefined` on path [undefined]...
[BOOT/INFO] -> `require_if_not_undefined` doesn't like this path
[BOOT/INFO] Checking path `/var/puter` for working directory...
[BOOT/INFO] -> doing `skip_if_not_exists` on path `/var/puter`...
[BOOT/INFO] -> `skip_if_not_exists` doesn't like this path
[BOOT/INFO] Checking path `/opt/puter/app/volatile/runtime` for working directory...
[BOOT/INFO] -> doing `skip_if_not_in_repo` on path `/opt/puter/app/volatile/runtime`...
[BOOT/INFO] -> doing `require_write_permission` on path `/opt/puter/app/volatile/runtime`...
[BOOT/ERROR] Error: Cannot write to path: /opt/puter/app/volatile/runtime
    at require_write_permission (/opt/puter/app/packages/backend/src/boot/RuntimeEnvironment.js:78:19)
    at RuntimeEnvironment.get_first_suitable_path_ (/opt/puter/app/packages/backend/src/boot/RuntimeEnvironment.js:282:32)
    at RuntimeEnvironment.init_ (/opt/puter/app/packages/backend/src/boot/RuntimeEnvironment.js:200:37)
    at RuntimeEnvironment.init (/opt/puter/app/packages/backend/src/boot/RuntimeEnvironment.js:182:18)
    at Kernel._runtime_init (/opt/puter/app/packages/backend/src/Kernel.js:50:20)
    at Kernel.boot (/opt/puter/app/packages/backend/src/Kernel.js:57:14)
    at file:///opt/puter/app/run-selfhosted.js:18:3
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
    at async loadESM (node:internal/process/esm_loader:28:7)

┏━━ [ HELP: `Cannot write to path: /opt/puter/app/volatile/runtime` ]
┃ Whoops! Looks like something isn't working!
┃ No help is available for this error.
┃ Help can be added in src/errors/error_help_details.
┗━━ [ END HELP ]

**Comment by venkadeshshiva** [comment]
Same issue here. any fix for this?

**Comment by frankzzw** [comment]
> Same issue here. any fix for this?

It seems like a container issue. I tried tweaking the settings in the YAML file, but to no avail. Waiting for a fix

**Comment by KernelDeimos** [comment]
I'm investigating this issue now

**Comment by KernelDeimos** [comment]
For some reason [this check](https://github.com/HeyPuter/puter/blob/a973f6609289ab96ca127edfaa55eb65c1cd8ad3/packages/backend/src/boot/RuntimeEnvironment.js#L155) appears to be failing; continuing to investigate...

**Comment by KernelDeimos** [comment]
My previous comment was incorrect; the repo is copied to `/opt/puter/app` so `/opt/puter/app/volatile` should be correct.

If you run this, are you able to access that directory from the shell?
```
docker exec -it <container id> ash
```

**Comment by venkadeshshiva** [comment]
In my case, Container keeps on restarting. so unable to execute the command.

**Comment by frankzzw** [comment]
> My previous comment was incorrect; the repo is copied to `/opt/puter/app` so `/opt/puter/app/volatile` should be correct.
> 
> If you run this, are you able to access that directory from the shell?
> 
> ```
> docker exec -it <container id> ash
> ```
same to @venkadeshshiva  ，The status of the container in 'docker ps' shows continuous Restarting. Unable to enter.

**Comment by KernelDeimos** [comment]
[latest commit](https://github.com/HeyPuter/puter/commit/c90931d00435cbd7fe40683cafa7809e726cb3c9) should fix the issue. The volumes for config and runtime were pointing to invalid directories.

**Comment by KernelDeimos** [comment]
@shuguet I'd like your input here since you wrote this configuration initially - my change fixes the issue but I'm not sure if it's what you were trying to do

**Comment by venkadeshshiva** [comment]
> [latest commit](https://github.com/HeyPuter/puter/commit/c90931d00435cbd7fe40683cafa7809e726cb3c9) should fix the issue. The volumes for config and runtime were pointing to invalid directories.

@KernelDeimos Still facing the same issue. container keeps on restarting.

**Comment by shuguet** [comment]
Grabbing a laptop, give me a minute.

**Comment by shuguet** [comment]
I was able to reproduce

The issue wasn't the folder name, it is the permissions (Actually, the UID/GID).

My bad, I should have checked in an empty folder, since my folder already had `data` and `config` set with the proper UID/GUI, it worked.

Can I revert the folder names to `data` and `config`?
Those are more idiomatic in Docker.
Also, `volatile` isn't actually volatile, since data will be preserved between runs, outside of the container.
I'll update the instructions, as this is what's actually failing.

In the meantime, the workaround is to replace those instructions for Docker Compose:
```mkdir puter && cd puter
wget https://raw.githubusercontent.com/HeyPuter/puter/main/docker-compose.yml
docker compose up```

By thoses:
```mkdir puter && cd puter
mkdir data config
sudo chown -R 1000:1000 config data
wget https://raw.githubusercontent.com/HeyPuter/puter/main/docker-compose.yml
docker compose up```

Checking the equivalent for the pure Docker one-liner, will update in a minute.

Can I throw a quick PR at you @KernelDeimos?
Are you okay with keeping `data` and `config`?

**Comment by shuguet** [comment]
This is the workaround in "pure" Docker mode (Without Compose):
```
mkdir puter && cd puter && mkdir config data && sudo chown -R 1000:1000 config data && docker run --rm -p 4100:4100 -v `pwd`/data:/opt/puter/app/volatile/runtime -v `pwd`/config:/opt/puter/app/volatile/config ghcr.io/heyputer/puter
```

**Comment by KernelDeimos** [comment]
The name of the `volatile` directory is appropriate during development when you need to repeatedly delete its contents to test different situations (testing/developing things that happen only on first run, for instance). I'm open to using a name that's more appropriate for general use.

One minor issue with _not_ using this directory in the container; a direct run in the container vs using docker will have different data. If someone logged into a user on a docker run, then switched to a dev run, they'll need to clear their local storage in order for the website to work at all. It makes me think that we should either have Docker use these directories, or change `RuntimeEnvironment.js` to use the ones you've suggested.

I like the idea of having these directories inside a directory (i.e. `volumes/config` and `volumes/data`), that way anything that might be changed by code can only reside in one directory and that directory is `.gitignore`'d.

**Comment by shuguet** [comment]
I consider running in Docker more akin to running in Production though (even though it's not product ready yet, but you get the idea).

We could (I can) propose a different `puter-dev` container image specifically for development (so-called devcontainer).
That's what I use on a number of other project.
But the "main" image should be meant for production, or at least something closer to a `staging`/`unstable` in other OS distributions.
In other words, not production ready, but not meant to develop, since if you're going to develop new code for Puter anyway, you're going to need to retrieve your modifications and commit them, which isn't want this container is supposed to be doing (despite the presence of `git` in the image, I only added it since your code seemed to try to run it to figure out it's version).

Does that make sense?

Regarding the volume aspect... if there was more than 1 container as part of the Compose, the idiomatic way is to have something like this:
```
puter/
├── docker-compose.yaml
├── puter
│   ├── config
│   └── data
├── service2
│   └── data
└── service3
    └── certs
```

With `service2` and `service3` being other services described in the `docker-compose.yaml` file.

For now, I can move the `config` and `data` folders to be nested inside a `puter` directory at the same level as the `docker-compose.yaml` file, for future proofing (say, for example, if you wanted to include a dependancy to a database backend for production, like PGSQL or MariaDB/MySQL or something).

**Comment by shuguet** [comment]
In other words, you shouldn't be running the `docker compose up` (or the `docker run ...`) commands in a git tree of Puter, but in a separate folder.
I've only added those 2 folders to .gitignore, because I knew someone was bound to do that, and I didn't want to risk a leak of data/config :P

**Comment by KernelDeimos** [comment]
Would `docker-compose` in the root of a repository usually be expected not to be a devcontainer? We don't really need a devcontainer since our dependencies are pretty straightforward, so I think that works.

What we expect for a production deployment is to have these directories exist:
- `/etc/puter` for configuration
- `/var/puter` for data

If these directories are created in the container (so they could be the volumes bound to `config` and `data`) then Puter won't try to use the `volatile` directory and it will use these instead.

I'm having a little bit of difficulty accepting that these directories (`puter/data` and `puter/config`) will be created in the repository's directory for production deployments. Is this what devlops people will expect or can we do better than that?

**Comment by KernelDeimos** [comment]
Now that I've looked at your PR I think I understand this differently now; so it's not necessary that somebody creates this `puter` directory inside the `puter` repo, but we `.gitignore` it in case that's where they create it. Otherwise, as a better practice, they might create these directories in a different place where they typically manage container data. Did I get that right?

**Comment by shuguet** [comment]
> Would `docker-compose` in the root of a repository usually be expected not to be a devcontainer? We don't really need a devcontainer since our dependencies are pretty straightforward, so I think that works.

Not necessarily no.
Usually the main `docker-compose.yaml` file is expected to run production, or close to it, and not have any un-necessary dependencies.
When a devcontainer is needed, there's usually a `CONTRIBUTING.md` file with specific instructions on how to setup a dev environment and run such devcontainer.

> Now that I've looked at your PR I think I understand this differently now; so it's not necessary that somebody creates this puter directory inside the puter repo, but we .gitignore it in case that's where they create it. Otherwise, as a better practice, they might create these directories in a different place where they typically manage container data. Did I get that right?

Exactly.
Consider this as me adding suspenders to the belt (sorry, I can't provide a parachute along with it...)

> What we expect for a production deployment is to have these directories exist:
> 
> * `/etc/puter` for configuration
> * `/var/puter` for data

I can tweak the `docker-compose.yaml` to reflect that, if you want?

**Comment by KernelDeimos** [comment]
> I can tweak the docker-compose.yaml to reflect that, if you want?

Yeah, let's update that. I'm gonna try it myself in the meantime to make sure that doesn't break anything.

**Comment by shuguet** [comment]
> Yeah, let's update that.

Done.

> update: That configuration seems to work as expected
🎉
