### ISSUE TITLE
Menu bar vanished

### ISSUE THREAD

**Issue by hoanglong226268** [HeyPuter/puter#319]
**Issue Description**
I can't see my menu bar after I cancel invite from my friend
**Steps to Reproduce**
Clicked on the invite link from someone and tick "X" instead of create account it will happened
**Expected & Actual Behavior**
I can't see my menu bar to log in account. However, I can see it in inprivate mode of Edge browser
**Addition Information or Screenshots (if applicable)**
It was happened in Edge browser
![image11](https://github.com/HeyPuter/puter/assets/61681976/1da1b274-536a-4390-941e-cb67e6a005f6)
**Tooling**
- [ ] Development (`npm run start`)
- [ ] Docker (via `docker run`)
- [ ] Docker (via `docker-compose`)

**Puter version (if accessible)**
v2.1.0

**Comment by KernelDeimos** [comment]
Can you send us a screenshot of the `console` and `network` tabs in the developer tools panel? In most browsers this can be accessed by entering Ctrl+Shift+i

**Comment by hoanglong226268** [comment]
> Can you send us a screenshot of the `console` and `network` tabs in the developer tools panel? In most browsers this can be accessed by entering Ctrl+Shift+i

Here is network
![Network](https://github.com/HeyPuter/puter/assets/61681976/5261c2b4-7313-4eb4-a527-34aba4fcadb9)
And here is console
![Console](https://github.com/HeyPuter/puter/assets/61681976/c7e02b35-3785-45f7-87b5-06ebefcd8bad)

**Comment by jelveh** [comment]
This has been resolved.

**Comment by hoanglong84** [comment]
> This has been resolved.

Why I still can't
![image](https://github.com/user-attachments/assets/dab3fdb2-3d8a-437b-8454-189a580be9f7)
