### ISSUE TITLE
Can't create folder

### ISSUE THREAD

**Issue by Zac0511** [HeyPuter/puter#584]
**Issue Description**
I tried to create a folder, and it doesn't works

**Steps to Reproduce**
Create a new folder, then refresh

**Expected & Actual Behavior**
Create the folder

**Addition Information or Screenshots (if applicable)**

https://github.com/HeyPuter/puter/assets/83874244/5e889a51-5a02-400f-b2c5-bb1bb623409d

**Deployment**
- [X] Production (puter.com)
- [ ] Development (`npm run start`)
- [ ] Docker (via `docker run`)
- [ ] Docker (via `docker-compose`)

**Puter version**
Version: 2.1.0 • Server: london • Deployed: 10/07/2024 18:56:26

**Comment by otlet** [comment]
Its not only bug on creating folder. I try to open puter.com site and got this same:
![obraz](https://github.com/HeyPuter/puter/assets/1035900/33247e4c-6f6f-4b2d-9c68-c6c30ec27767)

**Comment by jelveh** [comment]
Hey all, this should be resolved now, could you please give it another try?

**Comment by Zac0511** [comment]
still broken, but they appeared a few hours later. its like really long lag

**Comment by Zac0511** [comment]
The problem got fixed, i'm closing this
